version: '3.3'
services:
  adminservice:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - admin_db

  admin_db:
    image: mysql:5.7.33
    environment:
      MYSQL_DATABASE: adminservice
      MYSQL_USER: phpmyadmin
      MYSQL_PASSWORD: asd123ASD!@
      MYSQL_ROOT_PASSWORD: asd123ASD!@

    volumes:
      - ./storage/dbdata:/var/lib/mysql
    ports:
      - 33060:3306